"""blog_image

Revision ID: 094483b3354a
Revises: 869b61a2c064
Create Date: 2020-04-03 14:24:11.271088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '094483b3354a'
down_revision = '869b61a2c064'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_post', sa.Column('blog_image', sa.String(length=64), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog_post', 'blog_image')
    # ### end Alembic commands ###
