"""New Life 12

Revision ID: 14c2c0cfcea2
Revises: 5a7300e40934
Create Date: 2020-09-03 20:28:50.740538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14c2c0cfcea2'
down_revision = '5a7300e40934'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_projects',
    sa.Column('blog_project_id', sa.Integer(), nullable=False),
    sa.Column('blog_post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('project_name', sa.String(length=140), nullable=False),
    sa.Column('project_short_info', sa.Text(length=300), nullable=False),
    sa.Column('project_link', sa.String(length=100), nullable=False),
    sa.Column('project_image', sa.String(length=140), server_default='default_project.jpg', nullable=False),
    sa.ForeignKeyConstraint(['blog_post_id'], ['blog_post.blog_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('blog_project_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog_projects')
    # ### end Alembic commands ###
