"""New Life 7

Revision ID: 1a90078f6223
Revises: 2b6551b59dc4
Create Date: 2020-05-27 22:51:50.643881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a90078f6223'
down_revision = '2b6551b59dc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_post', sa.Column('country', sa.String(length=140), server_default='earth', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog_post', 'country')
    # ### end Alembic commands ###
