"""New Life 5

Revision ID: 2b6551b59dc4
Revises: 8fe4432782ac
Create Date: 2020-05-20 23:40:38.903315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b6551b59dc4'
down_revision = '8fe4432782ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_post', sa.Column('problem_type', sa.String(length=140), server_default='test_type', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog_post', 'problem_type')
    # ### end Alembic commands ###
