"""New Life 8

Revision ID: 33320a90055a
Revises: 1a90078f6223
Create Date: 2020-06-09 22:52:03.785848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33320a90055a'
down_revision = '1a90078f6223'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_info',
    sa.Column('blog_info_id', sa.Integer(), nullable=False),
    sa.Column('blog_post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['blog_post_id'], ['blog_post.blog_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('blog_info_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog_info')
    # ### end Alembic commands ###
