"""UpchangesX

Revision ID: 6e6ecab1b47f
Revises: 8bf07b35c94c
Create Date: 2021-03-26 23:56:22.784499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e6ecab1b47f'
down_revision = '8bf07b35c94c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upchangesx_email',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_upchangesx_email_email'), 'upchangesx_email', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_upchangesx_email_email'), table_name='upchangesx_email')
    op.drop_table('upchangesx_email')
    # ### end Alembic commands ###
