"""sixth migration

Revision ID: 869b61a2c064
Revises: 6af76ddce0fa
Create Date: 2020-03-22 10:19:22.630338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '869b61a2c064'
down_revision = '6af76ddce0fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('middle_name', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'middle_name')
    # ### end Alembic commands ###
