"""New Life 9

Revision ID: 89976e876c2f
Revises: 33320a90055a
Create Date: 2020-06-23 23:14:52.385348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89976e876c2f'
down_revision = '33320a90055a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_idea',
    sa.Column('blog_idea_id', sa.Integer(), nullable=False),
    sa.Column('blog_post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['blog_post_id'], ['blog_post.blog_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('blog_idea_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog_idea')
    # ### end Alembic commands ###
