"""empty message

Revision ID: d0d040e970fc
Revises: 5b4ddf50a144
Create Date: 2020-04-03 17:37:46.335728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0d040e970fc'
down_revision = '5b4ddf50a144'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_post', sa.Column('blog_image', sa.String(length=64), server_default='default_blog.jpg', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog_post', 'blog_image')
    # ### end Alembic commands ###
